- carrier/Dockerfile
- carrier/gefyra-carrier.conf
- carrier/setprobe.sh
- carrier/setroute.sh
- client/gefyra/__main__.py
- client/gefyra/api/bridge.py
- client/gefyra/local/bridge.py
- operator/gefyra/carrier.py
- operator/gefyra/handler/interceptrequests.py
- operator/gefyra/resources/crds.py
- operator/gefyra/utils.py
> feat: lets Carrier serves httpGet probes

- cargo/Dockerfile
- cargo/root/wgquick.patch
- client/gefyra/configuration.py
- client/gefyra/local/utils.py
> fix(cargo): fix cargo setup to work with WSL2 default linux

- client/gefyra/configuration.py
> fix: remove alpine container remainder

- client/gefyra/__main__.py
- client/gefyra/configuration.py
- client/gefyra/local/check.py
> fix: check Docker init, better error handling for CLI

- .github/workflows/docker-build-multiarch.yaml
- .github/workflows/python-tester.yaml
- .pre-commit-config.yaml
- client/gefyra/__main__.py
- client/gefyra/api/up.py
- client/gefyra/cluster/manager.py
- client/gefyra/cluster/resources.py
- client/gefyra/configuration.py
- client/gefyra/local/cargoimage/Dockerfile.py
- client/gefyra/local/utils.py
- client/poetry.lock
- client/pyproject.toml
- client/tests/test_up_args.py
- setup.cfg
> Allow custom registry and image urls

- install.sh
> Add installation script

- .github/workflows/python-tester.yaml
- client/gefyra/__main__.py
- client/gefyra/api/list.py
- client/gefyra/local/bridge.py
Fixes #59 
Exemplary output:
```
NAME                          IP_ADDRESS
mypyserver                    192.168.134.2
```
> Add gefyra list --containers

- client/gefyra/__main__.py
> chore: add hint when no flag is used for unbrige

- .github/workflows/python-tester.yaml
- client/gefyra/api/bridge.py
- client/gefyra/cluster/resources.py
I think the check for the container is still missing. Fix #70
> fix(#70): exit process when no pod for bridging can be found

- client/gefyra/local/bridge.py
- client/gefyra/local/networking.py
> fix: add another solution for docker network creation

- .github/workflows/python-tester.yaml
- client/gefyra/__main__.py
- client/gefyra/api/bridge.py
- client/gefyra/local/utils.py
Adds port mapping flag `--ports` to `gefyra run` command. Resolves #106.
> feat(#106): add port mapping flag / parser

- client/gefyra/api/bridge.py
- client/gefyra/local/bridge.py
- operator/gefyra/handler/interceptrequests.py
- operator/gefyra/resources/events.py
Branch created for simpler review.
> refactor: wait for bridge establish

- .github/workflows/python-tester.yaml
- client/gefyra/api/bridge.py
- client/gefyra/cluster/resources.py
- operator/gefyra/handler/interceptrequests.py
- operator/gefyra/resources/events.py
> fix(#107): bug when multiple bridges are created

- client/gefyra/__main__.py
- client/gefyra/api/list.py
- client/gefyra/local/bridge.py
- client/poetry.lock
- client/pyproject.toml
Add tabulate to format tables.
Refactor `get_all_containers` to add namespace to tuple.
> feat(#116): add namespace to container list

- .github/workflows/dist-build-mac.yaml
> fix: naming for MacOS binary

- .github/workflows/python-tester.yaml
- client/gefyra/__main__.py
- client/gefyra/local/utils.py
Flip argument order for port flag to work same as docker cli.
Allow to set host ip optionally.
Resolves #119
> refactor: `--port` flag for portmapping

- client/gefyra/__main__.py
- client/gefyra/api/bridge.py
- client/gefyra/api/down.py
- client/gefyra/api/list.py
- client/gefyra/api/run.py
- client/gefyra/configuration.py
- client/gefyra/local/__init__.py
- client/gefyra/local/cargo.py
- client/gefyra/local/minikube.py
- client/gefyra/local/networking.py
- client/gefyra/local/utils.py
- client/poetry.lock
- client/pyproject.toml
- client/tests/test_up_args.py
> feat: introduce --minikube switch with auto conf detection

- install.sh
> feat(#79): more empathetic install feedback

- client/gefyra/__main__.py
- client/gefyra/api/up.py
- client/gefyra/configuration.py
- client/gefyra/local/cargo.py
- client/gefyra/local/cargoimage/Dockerfile.py
- client/gefyra/local/utils.py
- client/tests/test_up_args.py
> feat(client): add --wireguard-mtu argument; default to 1340

- client/gefyra/__main__.py
- client/gefyra/local/utils.py
- client/tests/test_cli_utils.py
> feat(client): read endpoint connection from kubeconfig

- client/poetry.lock
- client/pyoxidizer.bzl
- client/pyproject.toml
> bump docker-py

- client/gefyra/api/bridge.py
> feat: add bridge information after successful establish

- .github/workflows/python-tester.yaml
- client/gefyra/__main__.py
- client/gefyra/api/bridge.py
- client/gefyra/api/down.py
- client/gefyra/api/list.py
- client/gefyra/api/run.py
- client/gefyra/api/up.py
- client/gefyra/configuration.py
- client/gefyra/local/__init__.py
- client/gefyra/local/utils.py
- client/tests/test_up_args.py
- setup.cfg
> feat: store kubeconfig as label on Cargo container

- .github/workflows/python-tester.yaml
- client/gefyra/__main__.py
- client/gefyra/api/__init__.py
- client/gefyra/api/status.py
- client/gefyra/local/__init__.py
- client/gefyra/local/cargo.py
- client/gefyra/local/utils.py
> Add `gefyra status` API and command

- client/gefyra/__main__.py
- client/gefyra/api/run.py
- client/gefyra/local/bridge.py
> feat: add --rm flag to gefyra run; now defaults to false

- client/pyoxidizer.bzl
> fix: docker deps for pyoxidizer build

- .github/workflows/python-tester.yaml
- client/gefyra/api/bridge.py
> fix(#199): use correct kubeconfig for unbridge

- .github/workflows/python-tester.yaml
This test has been flaky in the past. I couldn't get it to fail during this PR, so I just add some debug output.
> debug(status/cd): print gefyra status and try to fail

- carrier/gefyra-carrier.conf
> fix(#200): change carrier.log to /tmp/error.log

- .github/workflows/python-tester.yaml
- client/gefyra/__main__.py
- client/gefyra/api/run.py
> feat: add detach flag to cli

- operator/gefyra/resources/deployments.py
> chore(#221): add readiness probe for stowaway

- .github/workflows/python-linter.yaml
- .github/workflows/python-publish.yaml
- .github/workflows/python-tester.yaml
> fix(#241): pin python version for Github actions

- .github/workflows/python-tester.yaml
> feat(#253): run tests for multiple k8s versions

- .github/workflows/dist-build-mac.yaml
- .github/workflows/mac_binary_check.yaml
> test: add sanity check for mac binary

- .github/workflows/python-tester.yaml
> fix: low timeout for gefyra up

- .github/workflows/python-tester.yaml
- client/gefyra/configuration.py
- client/gefyra/local/bridge.py
- return empty list of no intercept request / namespace found
- add integration tests for
- alternative docker context
- invalid endpoint
> test: add tests for better coverage

- client/gefyra/cluster/manager.py
Adds error message for forbidden service account creation.
> chore: add human-friendly error message

- .github/workflows/python-tester.yaml
- client/gefyra/api/bridge.py
- client/gefyra/api/run.py
- client/gefyra/api/utils.py
- client/gefyra/cluster/resources.py
- client/gefyra/local/bridge.py
Resolve #244 
Resolve #245
Resolve #16
> Resolve bridge issues 

- .github/workflows/python-tester.yaml
> ci: add waits before bridging again

- .github/workflows/dist-build-mac.yaml
> fix: run mac codesign on publish only

- .github/workflows/binary_checks.yaml
- .github/workflows/dist-build-linux.yaml
> chore: bump ubuntu ci/cd image

- .github/workflows/python-tester.yaml
> chore(#278): do not fail fast on matrix

- .github/workflows/python-tester.yaml
- client/gefyra/__main__.py
- client/gefyra/configuration.py
> chore: check whether default kubeconfig exists

- .github/workflows/python-tester.yaml
> CI Pipeline - Docker Image Build Optimization / PyTest singular execution

- .github/workflows/binary_checks.yaml
> chore: fix track for binary checks

- .github/workflows/python-tester.yaml
> fix: no track for pytest

- .github/workflows/python-tester.yaml
- client/gefyra/api/bridge.py
- client/gefyra/cluster/resources.py
- testing/workloads/hello.yaml
Gefyra now checks whether pods have a command defined before bridging. If that is the case the bridging operation is rejected and Gefyra exits.
Resolve #211
> feat(#211): add command check for pods

- client/gefyra/__main__.py
- client/gefyra/local/bridge.py
> fix(#302): missing exeception raise

- .github/workflows/python-tester.yaml
- client/gefyra/__main__.py
- client/gefyra/api/run.py
> feat: add KeyboardInterrupt/EOF handling to gefyra

- .github/workflows/python-tester.yaml
- operator/Dockerfile
> fix(#312): poetry installation

- client/gefyra/api/run.py
> fix(#328): add check for healthy pod/container

- client/gefyra/api/run.py
- client/gefyra/local/bridge.py
> fix(#335): raise exeption for not running container

- .github/workflows/python-tester.yaml
> chore: bump k3d versions

- client/gefyra/configuration.py
> fix(#351): check for docker os rather than host os

- README.md
> fix(#374): broken readme link

- client/gefyra/local/__init__.py
- client/gefyra/local/utils.py
Generates a label with a unique bridge id on container creation.
> feat: add unique bridge id on container run

- client/gefyra/local/check.py
> chore: more verbose output for gefyra check

- .pre-commit-config.yaml
- client/gefyra/__main__.py
- client/gefyra/api/__init__.py
- client/gefyra/api/reflect.py
- client/gefyra/api/utils.py
- client/gefyra/cluster/manager.py
- client/gefyra/cluster/utils.py
- client/tests/e2e/base.py
- testing/workloads/hello.yaml
> feat(#150): add reflect command

- client/gefyra/configuration.py
- client/gefyra/local/cargoimage/cargo_dockerfile.py
Provide a better host resolution / add wg-patch for WSL.
> Host resolution

- .github/workflows/python-tester.yaml
- stowaway/root/defaults/server.conf
> chore(#462): add ip4 forward in stowaway server conf

- client/gefyra/cli/run.py
- client/tests/e2e/base.py
> fix(#474): required connection name

- client/gefyra/api/run.py
> fix(#465): silent error message (warning)

- .github/scripts/get_version.py
- .github/workflows/dist-build-linux.yaml
- .github/workflows/dist-build-mac.yaml
- .github/workflows/dist-build-windows.yaml
- .github/workflows/python-publish.yaml
- client/gefyra/cli/main.py
- client/gefyra/cli/self.py
> Adapt binary builds

- client/gefyra/cli/run.py
- client/gefyra/cli/utils.py
- client/tests/unit/test_cli_utils.py
> fix(#500): better argument parsing for the CLI

- carrier/gefyra-carrier.conf
> fix(#604): set cache dirs for carrier nginx

- client/gefyra/api/__init__.py
- client/gefyra/api/operator.py
- client/gefyra/cli/main.py
- client/gefyra/cli/operator.py
> chore: add operator update func and cli command

- README.md
Fix url to https://www.linuxserver.io/ in README
> Update README.md linuxserver url

- operator/gefyra/connection/stowaway/resources/configmaps.py
- stowaway/root/etc/s6-overlay/s6-rc.d/init-wireguard-confs/run
- remove curl in wireguard confs run
- add ip get in stowaway config map creation
closes #701
> feat: move icanhazip curl to operator :sparkles:

- client/gefyra/cli/main.py
Adds flag for logging with the python kubernetes client. Closes #797
> add --debug-kubernetes flag

- client/gefyra/api/connect.py
- client/gefyra/local/networking.py
- client/tests/unit/test_subnet_negotiation.py
> fix(#802): subnet negotiation
