install.sh

Since we run the command using sudo, the process is owned by root and
its group anyway, so we can just omit this info.

Fix installation on MacOS caused by missing group `root`.

---

client/gefyra/__main__.py
client/tests/test_version_command.py

Adds check whether there is a new version of gefyra published on
Github. Can be disabled by use `-n` or `--no-check` flag in `version`
command.
Simply parses Github release api page result and compares with current
version.

feat: add check for new version

---

stowaway/Dockerfile

The stowaway docker image for `arm64` contains the `coredns` binary for `amd64`.

fix stowaway docker image for arm64

---

client/gefyra/configuration.py
client/gefyra/local/bridge.py

Closes #75
Adds a check for the container status before deployment of container. If container is not running, an informative error message is displayed.

fix: check if container is running before deploying

---

.github/workflows/dist-build-mac.yaml
.github/workflows/python-tester.yaml
client/gefyra/__main__.py
client/gefyra/local/telemetry.py
client/gefyra/local/utils.py
client/poetry.lock
client/pyoxidizer.bzl
client/pyproject.toml

Adds telemetry for cli usage. Data will be published on gefyra.dev when available.
To collect the data the cli_tracking dependency (by Blueshoe) is needed which depends on Sentry's SDK. 
ToDo:

Telemetry for cli usage

---

.github/workflows/python-tester.yaml
client/gefyra/api/run.py

`--env-from` flag now allows following notation:
pod/podname1
deployment/deployment1
statefulset/statefulset1
pod/podname1/container-name
statefulset/statefulset1/container-name
deployment/deployment1/container-name
Resolves #130

feat: add kubernetes notation for `--env-from` flag

---

.github/workflows/python-tester.yaml
client/gefyra/__main__.py
client/gefyra/api/run.py

feat(client): fallback 'gefyra run' namespace from kubeconfig

---

.github/workflows/docker-build-multiarch.yaml
.github/workflows/python-tester.yaml

Bumps Docker Github actions. 
Adds inline caching information to builds. Can be retrieved for the next build then. Close #145

chore: update docker actions / use build caching

---

.github/workflows/python-tester.yaml
client/gefyra/__main__.py
client/gefyra/api/list.py
client/gefyra/configuration.py
client/gefyra/local/minikube.py
client/tests/test_up_args.py

This PR adds `--kubeconfig` and `--context`  flags to the gefyra CLI.
We want to use this flags in the planned Docker Desktop extension.
Closes #151

feat: add kubeconfig / context flag

---

client/gefyra/api/run.py

Improve workload types error message

---

.github/workflows/python-tester.yaml
README.md
client/gefyra/__main__.py
client/gefyra/api/bridge.py
client/tests/test_port_parser.py

Implements changes suggested in #137.
At the Kubernetes Community Days Munich @SteinRobert mentioned that this issue is waiting to be fixed, so here you go :-).
@Schille said "... automatically name bridges following this scheme: <namespace>/<pod>"
This doesn't work as Kubernetes resource names can't contain a slash. Therefore I replaced the slash with a dot.
I now removed the bridge name option completely as @Schille had the more convincing argument, but this decision is not mine to make.
Another improvement would be to automatically select the container if there is only a single one inside the pod.
This is only a draft. I am grateful for any criticism and feedback!

Improved DX for gefyra bridge action

---

client/gefyra/configuration.py

Resolves #210. Tested `status` and `run`.
We now set the context to whatever the context API tells us is set. In case the default is set we continue to init the docker client `from_env()`. Otherwise the endpoint from the given context is considered to init the Docker client.

feat(#210): add docker context handling

---

.github/workflows/python-tester.yaml
client/gefyra/api/status.py

Adds waiting time for status command to succeed.
Show correct status when Stowaway and/or Operator are not available yet.
Remove debug output from test.
Resolve #204

fix(#204): add wait time for status command

---

install.sh

@SteinRobert This is a quick follow up for the install script dependency checks based on @Schille comment in https://github.com/Getdeck/getdeck/pull/99

feat(installer): Check if `install` is available before running installer

---

stowaway/root/defaults/server.conf

I have a problem when working with a remote cluster, where cargo doesn't has a connection to the internet or other services of the cluster. Cargo is already configured with the forward, adding it manually to stowaway fixed the connectivity issues for me.

fix: add ipv4 forward on stowaway

---

.github/dependabot.yml

FIx directory value for dependabot.

fix: dependabot github actions yaml format

---

client/gefyra/cluster/manager.py

This is required to run stowaway on PodSecurity Admission-enabled clusters and since it is only a label, it won't do any harm on other clusters.
Signed-off-by: Mara Sophie Grosch <littlefox@lf-net.org>

Add PodSecurity admission label to configure namespace as privileged

---

.github/workflows/binary_checks.yaml
.github/workflows/dist-build-windows.yaml

chore: add binary checks

---

client/gefyra/cluster/resources.py

Seems like `pod.spec` is optional, which can cause errors when trying to access `pod.spec.containers`.

fix: pod spec fail

---

client/gefyra/__main__.py
client/gefyra/configuration.py
client/gefyra/local/cargo.py
client/gefyra/local/minikube.py
client/gefyra/local/utils.py
client/tests/test_up_args.py

- change error text when wireguard probe fails
- default endpoint port to 31820
Addresses stuff in #217 
Fix #239

refactor(#217): `--endpoint` flag improvements

---

client/gefyra/__main__.py
client/pyoxidizer.bzl

`chardet` is now missing in our builds. Add manually. See references:
https://github.com/psf/requests/pull/6261
https://github.com/psf/requests/issues/6331
https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/534

fix: missing dependency in pyoxidizer build

---

client/gefyra/api/run.py
client/gefyra/cluster/resources.py
client/gefyra/cluster/utils.py
client/tests/e2e/base.py

Fixes behaviour which might cause Gefyra to select a pod which actually does not belong to a deployment or statefulset. Instead of label_selectors it now works with a field_selector which leverages the owner reference / uuid of the deployment/ statefulset.

fix(#330): use owner ref / field selector for env

---

client/gefyra/local/utils.py
client/tests/unit/test_cli_utils.py

fix(#361): split of paths for volume mounts

---

client/gefyra/cluster/resources.py

Ignore 404 for replicasets. If not found we simply return false, since the ownership is not referenced or valid..

fix: owner_ship reference check

---

client/gefyra/api/run.py
client/gefyra/api/utils.py
client/tests/unit/test_cli_utils.py

Adds fix to only split env string on first equal sign. Adds test for env string splitting.
Refactors env string splitting for env_from and env overrides.
Fixes #385

fix: split var env vars containing '='

---

client/gefyra/api/run.py

Add additional search domains to `/etc/resolv.conf` matching those found in natural k8s pod.
Issue raised for discussion in #513

Extend DNS domains to match k8s

---

operator/gefyra/bridge/carrier/__init__.py

This fixes issues with the unbridge command, which was hanging and not restoring the original pod config (since it wasn't stored in the first place).
Fixes #488

fix: storing original pod config

---

client/gefyra/api/run.py
client/gefyra/cli/run.py
client/gefyra/local/bridge.py
client/tests/e2e/base.py

Add `--pull` and `--platform` flags to run
command. With these the user can specifiy whether
images should always be pulled and if (always)
a specific platform should be used.

chore: add `--pull` and `--platform` to run

---

.github/workflows/python-tester.yaml

Minikube in Github Actions is just too flaky. We tried several measure to reduce the flakiness, but never got rid of it.

chore: remove mac minikube test

---

.github/workflows/python-linter.yaml
client/gefyra/api/clients.py
client/gefyra/api/connect.py
client/gefyra/cli/clients.py
client/gefyra/cli/connections.py
client/gefyra/cli/updown.py
client/gefyra/configuration.py
client/gefyra/types.py
client/tests/unit/test_client_config.py
client/tests/unit/test_client_file_manipulations.py

- Added default MTU of 1340 to CLI commands for clients, connections, and up/down
- Updated client configuration to handle MTU setting more robustly
- Fixed a typo in an existing log message

fix: set default Wireguard MTU to 1340
